# Header

menu:
  主页: /
  # 相册: /photos
  #分类: /categories
  分享链接: /tags

# SubNav
subnav:
  github: "https://github.com/XuYuQuan0713"
  #weibo: "https://weibo.com/5095847284/profile?topnav=1&wvr=6"
  bilibili: "https://space.bilibili.com/286892977"
  rss: "atom.xml"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"

  #acfun: "#"
  mail: "mailto:934988029@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

#rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 网站运行时间，格式形如：“本站已安全运行 101 天 12 小时 13 分 41 秒”
# Runing Time
# running_time:
#   enable: true
#   create_time: '11/28/2014 12:00:00' #此处修改你的建站时间或者网站上线时间

# 文章太长，截断按钮文字
excerpt_link:
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: "展开全文"
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: "感谢你的赞赏"
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay:
# 微信二维码图片地址
weixin: /img/115.png

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: "创作ing..."

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ""
google_analytics: ""
favicon: /img/orange.svg

#你的头像url
avatar: /img/cat.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
# gitment:
# enable: true
# gitment_owner: false #XuYuQuan0713 #你的 GitHub ID
# gitment_remote: false
# gitment_repo: XuYuQuan0713.github.io #存储评论的 repo
# gitment_oauth:
#   client_id: 1fc62dd56cbe0576f99c #client ID
#   client_secret: 60c3ab1a78ca614a3326978669f482c68e96400f #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: "#006374"
  # gif:
  # enable: true
  path: /Touxiang/11.gif
  # 右滑板块背景
  slider: "linear-gradient(200deg,#a0cfe4,#e8c37e)"

#头像变换
#头像是否旋转(如果不要旋转取false)
avatarrotation: true

clinkLove:
  enable: true

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: "所有文章"
  friends: "友链"
  aboutme: "关于我"

friends:
  轻许xuxu: https://xuyuquan0713.github.io/

music:
  enable: true
  id: 1377748865 # 网易云分享的ID,ID可以随时替换
  autoplay: false # 是否开启自动播放

aboutme: <br>回首过去几年，<br>有种莫名的失败感<br>
author: orange
subtitle: "我们一起奔赴明天"

live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-hibiki # 模型：https://huaji8.top/post/live2d-plugin-2.0/ hanyou koharu /shizuku/hijiki/hibiki
  display:
    position: right
    width: 70
    height: 187
  mobile:
    show: true
